### ISSUE TITLE
Simplify and rename `lookahead`

### ISSUE THREAD

**Issue by wavebeem** [jneen/parsimmon#156]
**Breaking change suggestion**

Currently `lookahead` accepts multiple different types of arguments as shorthands, but in the interest of a consistent and predictable API we should change it to only accept a parser as its argument type.

Also, to be consistent with `notFollowedBy` it should be renamed to `followedBy`. So far I have strived to maintain good backwards compatibility in Parsimmon, so it might be worth keeping around `lookahead` as an alias. That being said, the function is undergoing a breaking change, so I think it's possibly better to just fully rename it so there are *obvious* errors when people migrate to the new version of Parsimmon.

Also up for discussion is the existence of non-method forms of these functions. `followedBy(...)` is equivalent to `P.of().followedBy(...)`, so we don't necessarily need both. Especially because `followedBy` doesn't really make sense in English without a subject to chain off of. But that second construction is a bit awkward looking, so 🤷‍♂️ 

Finally, the return value should be `null`, not an empty string.

**Comment by wavebeem** [comment]
Had another thought: it might be worth just returning the data that came back from the "lookahead" anyway? There's no good reason to drop it on the ground inside the parser itself, since generally it's gonna get ignored anyway...

**Comment by jneen** [comment]
But in the successful case there's no data at all for `notFollowedBy`...

**Comment by theqabalist** [comment]
For what it's worth, I couldn't find a way to do something like a checksum of data easily.  In Parsec, there is try, which will run the parser, but not consume the input.  I wanted to use lookahead to do this, but it returned nothing.  Basically, if I am at the start of a message, but after some sort of control structure, it would be nice to produce a value based off the rest of the message before it's converted into an AST.

One common example of this is HTTP request signing, where the body may have a parseable content type, beyond the HTTP parsing, but you need to process it raw first in order to provide or verify a signature.

So I do think that at least one function should be provided, maybe a variant of followedBy that returns what it peeked so that value can be operated on without consuming the input.

**Comment by jneen** [comment]
Aside, but there's gotta be a more efficient way than `any.times(size)`. Maybe `any` could take a size argument, default 1?

**Comment by wavebeem** [comment]
I wouldn't be opposed at all to a new constructor like `size(n)` that is a more efficient form of `any.times(n).tie()`

That seems like a totally reasonable use case for `lookahead` to me.

Also while we're at it… I need to think more about plans for version 2. I've got a small handful of breaking changes I've really been wanting to get in, but I keep getting cold feet about the idea of releasing a new major version…

**Comment by theqabalist** [comment]
I'm totally down to contribute in making a major revision smooth, just let me know what you need. This project has been a godsend for me at my job.

**Comment by wavebeem** [comment]
So as not to balloon this thread, I've created discussion around 2.x over here: https://github.com/jneen/parsimmon/issues/230

**Comment by halfzebra** [comment]
This probably doesn't help the ongoing discussion, but why is `.lookahead` returning an empty string instead of the parsed value?

Wouldn't it make sense to keep `.lookahead` and introduce new methods for matching values ahead without consuming the string?

**Comment by wavebeem** [comment]
Lookahead is just weird in general. I've definitely thought about what you're suggesting, but it's a change that wouldn't go out until I decide there should be a Parsimmon v2 anyway.

**Comment by theqabalist** [comment]
Should we just add a non consuming combinator? I'd be willing to implement it. It's super useful if you want to checksum something in addition to parsing it.

**Comment by wavebeem** [comment]
Like sub-parse checksum or something? Otherwise I'd pass off the whole input string.

I mean what you're describing almost exists already I'm just dumping the output on the floor. `lookahead(someParser)` is basically it.

**Comment by theqabalist** [comment]
well in binary frames the first byte is typically a length, so you generally checksum after that. I actually think adjusting lookahead to return the value is backwards compatible because anyone using it currently obviously isn't depending on that value.

**Comment by wavebeem** [comment]
ah, that makes sense.

i mean it is an API contract change since it does specify to return empty string right now, but you're also right in that it's extremely likely not to break anyone. but it makes me nervous 😞

**Comment by theqabalist** [comment]
Is it theoretically possible to produce a test case, even contrived, that demonstrates a breaking reliance on the value being null or undefined? Because if we cannot produce a test case then it's most likely impossible that the change is breaking. My hunch is that you cannot rely a value that is the embodiment of no information such a null. I'm not sure how to prove that more rigorously though.

**Comment by theqabalist** [comment]
I think you can make the argument from a category theory perspective. null represents the Unit / singleton type in the category of sets, which forms what's called an initial object. The definition of an initial object is that it has a unique morphism from itself to every object in the category (other types), which means that the morphism cannot represent a dependent transformation from Unit to any other type T. I would need someone to check this reasoning though. @arzig

**Comment by wavebeem** [comment]
I see what you're saying but also I've been on the receiving end of "harmless" breaking changes from numerous libraries before. Underscore in particular was a thorn in my side about this.

I'm fine to add a variant of lookahead that only takes parsers (not strings or regexp) and returns the parsed value if you'd like to make a PR for that.

**Comment by rzeigler** [comment]
While I think the argument regarding Unit as an output does not carry any information null has the additional behavior of being falsey whereas matched input would always certainly be truthy. So while I'm certain anyone depending on a value from lookahead is doing something silly it would technically be a breaking change.

**Comment by theqabalist** [comment]
I'm OK making a PR. What would we want to call it? Maybe `preview`?

**Comment by wavebeem** [comment]
Hmm. All the good names are already taken in this library, haha. I think `preview` is good, but I'm also considering `peek`.

**Comment by theqabalist** [comment]
I considered peek as well. I think if we use a confusingly similar name that we just document that "its a lookahead variant that returns it's value."

**Comment by wavebeem** [comment]
I don't have strong feelings about it either way.

**Comment by halfzebra** [comment]
Here are my two cents on the lookahead situation:

- I'm with @wavebeem, changes to the existing APIs are considered a breaking change in semver, even though realistically it's extremely unlikely that someone will experience a problem with this. 
- Bumping the major version is okay if the library is good at following semver because no one will suffer any issues.
- `Parsimmon.peek` is a good option, but in a current situation, it's more like `Parsimmon.lookaheadWithYield`(which has to be converted into `lookahead` with the next major release). In my defense, this naming is using an already existing glossary 🙂 

I hope this helps.

**Comment by jakepearson** [comment]
In case anyone needs it, I wrote a peek function that worked for me.

``` typescript
function peek<T>(parser: parsimmon.Parser<T>): parsimmon.Parser<T> {
  return parsimmon((input, i) => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const result = (parser as any)._(input, i);
    result.index = i;
    return result;
  });
}
```
Should be easy to convert to JS if you want.

**Comment by trafnar** [comment]
@jakepearson what is `_` in `const result = (parser as any)._(input, i);`?

**Comment by wavebeem** [comment]
`parser._(input, index)` is the internal implementation of custom parsers. It's similar to `parser.parse(input)` but it doesn't assert EOF afterward, it takes the starting index as a parameter, and the output format is a little different.

Perhaps it should be documented, but it hasn't really been a priority for me.
