### ISSUE TITLE
Custom validation inside Parsimmon

### ISSUE THREAD

**Issue by davidvuong** [jneen/parsimmon#184]
```
var x;
x = 1;
y = 2;
```

I'm trying to build a parser to parse the above but I want to build in validation around whether or not variables are defined before they can be set so in the above `x = 1` is accepted but `y = 2` should fail.

Is this something I can do within Parsimmon, should my parsers mutate state to keep track of defined variables or is there something else I should be doing? I think I'd just like a way to access to previously consumed values.

**Comment by wavebeem** [comment]
I would not recommend doing this inside Parsimmon. Static analysis should be performed after parsing. It's especially dangerous to perform mutations when parsing with Parsimmon because backtracking can happen at any point, leaving you with incorrect state.

Here's an example workflow for how to handle your question:

Start with this file input:

```js
var x;
x = 1;
y = 2;
```

Parse using Parsimmon into this data (AST):

```js
{
  name: "Program",
  value: [
    {
      name: "VariableDeclaration",
      value: {
        identifier: {
          name: "Identifier",
          value: "x"
        },
        initialValue: null
      }
    },
    {
      name: "AssignmentStatement",
      value: {
        identifier: {
          name: "Identifier",
          value: "x"
        },
        newValue: {
          name: "Number",
          value: 1
        }
      }
    },
    {
      name: "AssignmentStatement",
      value: {
        identifier: {
          name: "Identifier",
          value: "y"
        },
        newValue: {
          name: "Number",
          value: 2
        }
      }
    }
  ]
}
```

At this point, you will need to write a function which takes this data and walks through it, collecting `VariableDeclaration`s and then checking for any usage of variables that have not been declared.'

This is going to depend on how variable scoping works in your language, but the basic idea is a nested data structure representing layers of scope, along with a recursive function to walk through your whole AST.

Example: https://github.com/squiggle-lang/squiggle-lang/blob/master/src/linters/unused-or-undeclared.js

**Comment by wavebeem** [comment]
Feel free to ask if you have more questions about this, but I'm going to mark the issue as closed because there is no work to be done for Parsimmon here.

**Comment by wavebeem** [comment]
This new example I wrote may be useful to you: https://github.com/jneen/parsimmon/blob/master/examples/linter.js

**Comment by davidvuong** [comment]
Hey thanks @wavebeem. That makes a lot of sense and the linter example really helps. Cheers!
