### ISSUE TITLE
Reconsider varargs functions?

### ISSUE THREAD

**Issue by wavebeem** [jneen/parsimmon#186]
I think it would be better if `P.alt` and `P.seq` and `P.seqObj` and such took arrays of arguments instead of a variable number of arguments. It's easier to write code that wraps around them that way, and it formats much better with Prettier.

**Comment by praxiq** [comment]
Why do you say that it's "easier to write code" that way? With ES6 you can just write `P.alt(...array)` and get the desired functionality. Varargs feels more idiomatic to me in javascript. Plus, varargs instead of arrays save me two characters every time I call one of those functions, reducing the visual complexity of the code.

(And even for those stuck writing ES5, it's not too hard to call `apply` when you need it.)

**Comment by wavebeem** [comment]
i say it because using .apply is annoying and es6 `...array` is fine and all but i don't like the usability of parsimmon depending on it. plenty of folks aren't using es6 and won't be any time soon.

also i just think it makes more sense this way.

i wouldn't worry about it anyway, i don't have plans to release v2 soon.
