### ISSUE TITLE
Stateful parsers

### ISSUE THREAD

**Issue by fresheneesz** [jneen/parsimmon#209]
Creating a new issue for this, since there isn't one yet. For reference, there's some more discussion here: https://github.com/jneen/parsimmon/issues/204

@wavebeem I just realized that the way you implemented stateful parsers [here](https://runkit.com/wavebeem/59cdac70837de0001248bd64) means that `_` can no longer be used in `createLanguage` without breaking things. The docs for `createLanguage` use _ to mark whitespace (and so does the language I'm working on). I recommend changing the internal `_` to something like `__action` or somehow making it fully private.

**Comment by wavebeem** [comment]
I'm not following this at all. `this._` in createLanguage is completely different from `this._` in a Parsimmon parser. They are separate objects and there is no name collision.

As for stateful parsers… I'm still thinking the `withState` solution, but I haven't had time to look at it more.

**Comment by fresheneesz** [comment]
Ok, I think my problem with `_` was that I still hadn't converted one or two combinators to calling form (they were still left as `this.whatever` rather than `this.whatever()`). So maybe that was the only problem. I wanted to create this issue for discussion about stateful parsers tho, rather than discussing them in other unrelated tickets like we were doing.

**Comment by fresheneesz** [comment]
So in your implementation, `this` doesn't chain at all. So while ES6 arrow functions can usually grab the right `this`, "old" style functions and functions not defined inline will need to be bound to `this` or passed `this` as some other variable. Do you plan to chain this around so that extra binding isn't needed?

**Comment by wavebeem** [comment]
I'm explicitly binding `this` on all the parser returning functions already:

```js
    for (const [key, val] of Object.entries(parsers)) {
      const func = val.bind(this);
      if (val.length === 0) {
        const parser = P.lazy(func);
        this[key] = () => parser;
      } else {
        this[key] = func;
      }
    }
```

As for callbacks losing `this`… I mean there's nothing I can do about that. If you're not using ES6, my suggestion is simply `var self = this` (which Parsimmon makes use of internally). Or you can manually call `.bind(this)` on all your functions…

The alternative is using a parameter to the function instead `this`, thus sidestepping the binding issue. I suppose I could do it that way, but I'm not really sure it's better. I guess if I kept it that way then it would be backwards compatible with existing `createLanguage`, probably (if you think adding an extra param is backwards compatible—that's up for debate since it can break things). But then you have to name it in every single parser method.

**Comment by fresheneesz** [comment]
Wouldn't it be possible to pass the context from parser to parser? It would require that custom combinators (including all the internal ones) have a way to pass the state. Maybe instead of returning `Parsimmon(fuction(input,i) {...})` from a custom parser, you return `this.Parsimmon(fuction(input,i) {...})` and the call to Parsimmon would extract the state from `this` and bind it to itself? Then things like `chain` could just bind the correct context to their callback. I think that could probably eliminate the need for most if not all manual context binding.

**Comment by wavebeem** [comment]
Closing in favor of https://github.com/jneen/parsimmon/issues/210
