### ISSUE TITLE
Feedback requested from Parser Combinators authors

### ISSUE THREAD

**Issue by bd82** [jneen/parsimmon#226]
Hello again.

### Background
I've recently added a new (initial) capability to Chevrotain that makes it possible to be used as
the underlying engine for parser generators and **combinators**.
Basically instead of being a library for writing parsers it could also be used as a library for writing **other** libraries for writing parsers. 😄 

References:
* [Docs](http://sap.github.io/chevrotain/website/Deep_Dive/custom_apis.html)
* [Runnable example](https://github.com/SAP/chevrotain/tree/master/examples/custom_apis/)

### Feedback Request
- Do you think this would be useful for building parser combinator libraries?
- What is missing?
- Is there a scenario in which parsimmon would evaluate using this as its engine?
- Any other thoughts & feedback? 

Thanks in advance. 😄

**Comment by wavebeem** [comment]
Hi @bd82!

Congrats on the new feature!

## Initial thoughts

I looked through a few of the files for a little bit. `combinator_grammar.js` seems pretty reasonable to me. It looks like you register rules with names and can refer to them by string to avoid mutual recursion problems?

I did find the actual "parse" function a bit confusing since I'm not familiar with Chevrotain:

```js
module.exports = function(text) {
    const lexResult = JsonLexer.tokenize(text)

    if (lexResult.errors.length > 0) {
        throw Error("Sad Sad Panda, lexing errors detected")
    }

    // setting a new input will RESET the parser instance's state.
    jsonParserInstance.input = lexResult.tokens

    // step into the following statement to debug the generated chevrotain code.
    const value = jsonParserInstance.json()

    if (jsonParserInstance.errors.length > 0) {
        throw Error("Sad Sad Panda, parsing errors detected")
    }

    return {
        value: value,
        lexErrors: lexResult.errors,
        parseErrors: jsonParserInstance.errors
    }
}
```

Do you have to call the lexer separately from the parser? I would think the parser would just call it for you.

## Specific feedback

> Do you think this would be useful for building parser combinator libraries?

At first glance, yes, it probably would be useful.

> What is missing?

Well, Parsimmon has a _lot_ of functions and methods, and I'm not really sure how many parallel features Chevrotain has. The most obvious thing that was missing here was `.map` to transform the parsed results for the AST, which is fairly integral to Parsimmon. Though the new `.node` and `seqObj` functions in Parsimmon are solid helpers for constructing a good AST without explicit code.

> Is there a scenario in which parsimmon would evaluate using this as its engine?

If Chevrotain parser combinators are substantially faster than Parsimmon *and* can be used as the Parsimmon backend without breaking Parsimmon's API, I would consider it. Or if Chevrotain enabled substantially better developer experience (maybe better error messages, or something?).

Note that as of right Parsimmon also promises support for IE7 (!) and there would need to be a major version bump even to drop that.

> Any other thoughts & feedback?

The return value from parse in the specs is extremely big! Chevrotain is obviously embedding a lot of information in the AST by default whereas Parsimmon takes the opposite approach of asking the programmer to decide what goes into the AST. With Chevrotain is there any way to add actions (`.map` off of a parser) or otherwise influence the AST? Are there any helpers to write a tree transformer to take the Chevrotain AST and turn it into a simplified AST to pass off to the rest of your application?

Or maybe this parser just leaves a lot of information and that isn't required? I'm not entirely sure.

Parser output: https://gist.github.com/wavebeem/72a775dee82f748ddfa56e29587469e8

**Comment by bd82** [comment]
Thanks for the feedback!

> I looked through a few of the files for a little bit. combinator_grammar.js seems pretty reasonable to me. It looks like you register rules with names and can refer to them by string to avoid mutual recursion problems?

Yeah strings are used to avoid recursion issues, but keep in mind this is just a conceptual examples
showing one manner of how this capability **could** be used not how it must be used.

> Do you have to call the lexer separately from the parser? I would think the parser would just call it for you.

It is not mandatory, everything could be wrapped under a **single** parse.
It is just how I'm used to as Chevrotain has **distinct** lexing and parsing phases.

> The most obvious thing that was missing here was .map to transform the parsed results for the AST, which is fairly integral to Parsimmon.

"Native" Chevrotain works either by embedding actions in the parser code (just like hand crafting a parser), or by automagically creating a CST (Concrete Parse Tree) which contains more information than
an average AST. this CST can than be converted to an AST using a CST Visitor.

Right now embedded actions are not supported in the "custom APIs" scenario.
And my focus for the next version is to strengthen CST related capabilities (customization/labeling/reducing size of the structure). To make the CST scenario easier to use.

One of the scenarios could even be generalizing the automagical generation of the CST
so a custom API could generate all sorts of AST variants but that may be a longer term project.

I also need to consider if and how I could implement support for embedded actions
which could probably enable implementing.

I will add another comment...

**Comment by bd82** [comment]
> If Chevrotain parser combinators are substantially faster than Parsimmon and can be used as the Parsimmon backend without breaking Parsimmon's API, I would consider it. Or if Chevrotain enabled substantially better developer experience (maybe better error messages, or something?).

I suspect such a scenario would have to include breaking changes.
Just having a **distinct** lexing phase will cause changes.

From a performance perspective it should have the same speed as other Chevrotain parsers.
So that could be 1.5-3 times faster depending if a CST or embedded actions are used.
* Based on Json grammar benchmark on Chrome.

I think the main points of interest would be:
- Performance.
- Fault Tolerance.
- Full separation of grammar and semantics.

I also get the feeling the custom apis capabilities would need to mature before being considered for  use in a mature library and should perhaps be first attempted at a smaller scope (new library).

> The return value from parse in the specs is extremely big! Chevrotain is obviously embedding a lot of information in the AST by default whereas Parsimmon takes the opposite approach of asking the programmer to decide what goes into the AST. With Chevrotain is there any way to add actions (.map off of a parser) or otherwise influence the AST? Are there any helpers to write a tree transformer to take the Chevrotain AST and turn it into a simplified AST to pass off to the rest of your application?

Yes the CST is really big, as mentioned earlier I plan on improving it...
The basic flow is to transform the CST into an AST using a **CST Visitor**.
You can find a detailed explanation (and code samples) of this flow in a [POC created for JHipster-Core project](https://github.com/jhipster/jhipster-core/issues/144)

and docs about the CST [here](http://sap.github.io/chevrotain/website/Deep_Dive/concrete_syntax_tree.html) (transformations are at the bottom)

**Comment by bd82** [comment]
### My Understanding

* Custom AST/CST creation capabilities are important for potential adoption
   as not everyone is going to like the Chevrotain CST.

* The capability to use embedded actions to create even more custom flows would be very useful
  although I am not sure how feasible it is. 

* A Parser Generator scenario may be a better fit as these custom APIs feature relies on code
   generation (to file directly or using "new Function()" which will not work well in certain webpage.
   A Parser Generator on the other hand is already used to generating files to disc...

* Start with a smaller scope first, a mature library is not the best consumer due to backward compatibility issues.

Thanks again for the feedback @wavebeem 😄

**Comment by wavebeem** [comment]
> The capability to use embedded actions to create even more custom flows would be very useful
although I am not sure how feasible it is.

Yeah, this is big. Parsimmon allows arbitrary function code in any parser with its exposed API. If I understand correctly this would be a hard mismatch for using Chevrotain behind Parsimmon.

> A Parser Generator scenario may be a better fit as these custom APIs feature relies on code
generation (to file directly or using "new Function()" which will not work well in certain webpage.
A Parser Generator on the other hand is already used to generating files to disc...

Ah yeah, Parsimmon has zero `eval` or `Function(...)` so it can be used on pages with a no-eval restriction in its CSP.

> Start with a smaller scope first, a mature library is not the best consumer due to backward compatibility issues.

Feel free to message me in the issues/PRs if you want opinions on anything!

**Comment by wavebeem** [comment]
If you think this feedback is good enough for what you were wondering before, let me know and I can close the issue. But feel free to keep chatting in here if you have anything else to talk about! 😄

**Comment by bd82** [comment]
> Yeah, this is big. Parsimmon allows arbitrary function code in any parser with its exposed API. If I understand correctly this would be a hard mismatch for using Chevrotain behind Parsimmon.

Yeah this is the most difficult problem that may be out of scope for me.
However considering the complete separation of grammar and semantics (no embedded actions)
is fairly popular (antlr/Ohm/Chevrotain) I can live with that...

Thanks again.
This was very helpful 👍
