### ISSUE TITLE
Question: handling recursion properly

### ISSUE THREAD

**Issue by njlr** [jneen/parsimmon#227]
I have been trying to learn more about how this library works so I tried constructing a simple recursive language: 

```javascript
import P from 'parsimmon';

// A language for adding fives... 
// 5
// 5 + 5
// 5 + 5 + 5

const language = P.createLanguage({

  expression: r => P.alt(r.binaryExpression, r.number),

  binaryExpression: r => P.seqMap(
    r.expression, 
    r.operator, 
    r.expression, 
    (left, operator, right) => ({
      type: 'binary', 
      left, 
      operator, 
      right,
    })),

  number: r => P.string('5')
    .map(value => ({
      type: 'number', 
      value: Number(value), 
    }))
    .trim(P.optWhitespace), 

  operator: r => P.string('+')
    .map(value => ({
      type: 'operator', 
      value,
    }))
    .trim(P.optWhitespace), 

});

console.log(language.expression.tryParse('5'));
console.log(language.expression.tryParse('5 + 5'));
console.log(language.expression.tryParse('5 + 5 + 5'));
```

As you can probably guess, this results in a `RangeError: Maximum call stack size exceeded` error due to the recursion `expression -> binaryExpression -> expression`. 

 * How can I reorganize this parser so that it does not infinitely recurse? 
 * How would I approach left and right associativity?

**Comment by wavebeem** [comment]
## Looping issue

The problem here is that Parsimmon will just try to resolve the first thing it can repeatedly, and you have a loop.

`expression` tries to do `binaryExpression`,
then `binaryExpression` tries to do `expression`.

But you never consume any input during this. You need to use something more restrictive than `expression` in your `binaryExpression` rule.

In your case right now, I would suggest doing `P.seqMap(r.number, r.operator, r.expression)`, but if you want a full math parser, that will need to change eventually.

## Associativity

The easiest way to handle associativity is to use `P.sepBy1` and then manually arrange the list of results using `.reduce` or `.reduceRight` for left vs right associativity: https://runkit.com/wavebeem/5a9c5bd5bdde5f00132e773b

## Example

I wrote a full example of a math parser. It is a little dense, but it covers a pretty comprehensive form of math, and makes it easy to reason about precedence and associativity:

https://github.com/jneen/parsimmon/blob/master/examples/math.js

**Comment by njlr** [comment]
Thank you for your comments; the `.reduce` and `.reduceRight` examples were particularly helpful. 

For anyone stumbling upon this, here was my final implementation: 

```javascript
import P from 'parsimmon';

// A language for adding fives... 
// 5
// 5 + 5
// 5 + 5 + 5

const language = P.createLanguage({

  expression: r => P.alt(r.binaryExpression, r.simpleExpression),

  simpleExpression: r => r.number, 

  binaryExpression: r => P.seqMap(
    r.simpleExpression, 
    r.operator, 
    r.expression, 
    (left, operator, right) => ({
      type: 'binary', 
      left, 
      operator, 
      right,
    })),

  number: r => P.string('5')
    .map(value => ({
      type: 'number', 
      value: Number(value), 
    }))
    .trim(P.optWhitespace), 

  operator: r => P.string('+')
    .map(value => ({
      type: 'operator', 
      value,
    }))
    .trim(P.optWhitespace), 

});

console.log(language.expression.tryParse('5'));
console.log(language.expression.tryParse('5 + 5'));
console.log(language.expression.tryParse('5 + 5 + 5'));
```
```
