### ISSUE TITLE
Streaming input and output?

### ISSUE THREAD

**Issue by njlr** [jneen/parsimmon#229]
The `parse` function only seems to accept strings, but sometimes you have a stream of input. Buffering the entire stream into a string is not always feasible due to the size. 

Does the library provide a method to feed input incrementally to a parser?

**Comment by wavebeem** [comment]
Parsimmon currently only supports strings (open PR for binary Buffer support is being worked on: https://github.com/jneen/parsimmon/pull/228).

I'm not really sure how well streaming would fit into Parsimmon because of the input is too big to buffer at once, the AST result from Parsimmon is probably going to be even bigger (and not fit in memory).

I'm open to suggestions, but I don't know how this would work in Parsimmon, honestly.

**Comment by theqabalist** [comment]
I'm not sure that applicative/monadic parsers in general are really complementary to event-driven incremental parsing, like a sax parser.  Pulling from something like haskell, you'd be parsing into IO actions rather than values in order to do the event driven part, at least that's my initial impression.

Incremental parsing, just to end up with an in-memory AST, does not seem like it wouldn't actually produce anything of value because of @wavebeem's observation.

Does the input document not compose to smaller chunks that can be parsed inside of a stream construct rather than subsuming the stream in the parser?

**Comment by njlr** [comment]
> Incremental parsing, just to end up with an in-memory AST...

The output would also be piped as chunks, for example to a file. 

Imagine an AST parsed with a `.sepBy()`, such as a [JSON lines](http://jsonlines.org/) file. You could perform a transformation on each statement. However, the chunks you receive from the read stream might not be a complete statement. You need to keep adding more input until a sub-structure can parse. 

My current approach (using the existing `parse` function) would be: 

 1. Read file stream
 2. On each chunk... 
    2.1. Walk the length of the chunk + buffer; try to parse each substring... 
       2.1.1 If all substrings fail, we probably need more input. Buffer the chunk. 
       2.1.2 If some substring passes, clear the buffer and yield the AST. 

This approach is required because the `sepBy` character (`;`, `\n`, etc) might occur inside a string etc.

**Comment by wavebeem** [comment]
for JSON Lines at least, isn't it true that you can just split on `\n` to get separate JSON documents? since they don't use whitespace inside the JSON objects and all newline in strings in JSON have to be escaped?

i would think for JSONL you could keep buffering the lines until a new chunk includes `\n`, then send that entire buffered portion up to `\n` to Parsimmon.

i would think a similar approach could be applied to other streaming formats, but admittedly i've rarely worked with streaming formats so i can't really say for sure

**Comment by njlr** [comment]
Sorry, JSONL was probably a poor example in that case. Imagine a format where the split character can occur inside the list elements. 

Another reason to support incremental input would be efficiency. It would allow you to fail-fast if the input you have received so far could not possibly be valid.

**Comment by wavebeem** [comment]
If you have a more complicated example handy maybe we can discuss how this could fit into Parsimmon? I am a little worried though as I think to make streaming work natively inside Parsimmon we'd probably need to make it async, which is gonna be huge duplicate work…

**Comment by theqabalist** [comment]
This seems like something that you could use a stream construct for rather than building streaming into parsimmon.

```javascript
fromEvents(emitter, 'data')
  .split('')
  .scan((buffer, byte) => buffer + byte)
  .map(parse)
  .filter(failed)
```

That would be streaming pseudo code, lol, adjust for your favorite streaming library.

**Comment by theqabalist** [comment]
Though I suppose the scan needs a way of dropping parsed content.

**Comment by njlr** [comment]
Here is my solution using the Node.js streams API. Note how I am calling parse more times than necessary; it would be more efficient if I could feed characters to `tryParse`: 

```javascript=
import { Transform } from 'stream';

import { language } from './language.js';

export class ParseTransform extends Transform {

  constructor() {
    super({ objectMode: true });
    this.buffer = '';
  }

  _transform(chunk, encoding, callback) {
    const chunkAsString = chunk.toString(encoding || 'utf8');
    for (const c of chunkAsString) {
      this.buffer += c;
      try {
        // Try to parse the buffer. 
        const ast = language.program.tryParse(this.buffer);
        // Parse worked! Push the result... 
        this.push(ast);
        // The buffer should be emptied. 
        this.buffer = '';
      } catch (error) {

      }
    }
    callback();
  }
}
```

**Comment by theqabalist** [comment]
This was more the approach I was advocating.

```javascript
const {stream, sequentially} = require('kefir');
const {noneOf, wrap, letters, any, eof, string, alt} = require('parsimmon');
const {pathEq, prop, sequence, chain, identity} = require('ramda');

const space = string(' ');
const lpar = string('(');
const rpar = string(')');
const symbol = noneOf(' ()').atLeast(1).tie();
const _sexpr = symbol.sepBy1(space).wrap(lpar, rpar)
    .map(([f, ...args]) => ({f, args}));
const sexpr = alt(_sexpr, symbol).sepBy(space).wrap(lpar, rpar)
    .map(([f, ...args]) => ({f, args}));

let emit;

stream(emitter => {
    emit = emitter.emit.bind(emitter);
})
    .map(x => x.toString('utf8'))
    .flatMap(chunk => sequentially(0, chunk))
    .scan(({ast, buffer}, char) => {
        const parsed = sexpr.parse(buffer + char);
        return parsed.status ?
             {ast: parsed.value, buffer: ""} :
             {ast: null, buffer: buffer + char};
    }, {ast: null, buffer: ""})
    .filter(prop('ast'))
    .map(prop('ast'))
    .onValue(console.log);

emit('(+ x 5)');
// logs the full node

setTimeout(() => {
    emit('(lambda');
    console.log("waiting...");
    // nothing
}, 1000)

setTimeout(() => {
    emit(' (x)');
    console.log("still waiting...");
    // still nothing
}, 2000);

setTimeout(() => {
    emit(' (+ x 5))');
    // ast emitted
}, 3000);
```

This is a super basic s-expression parser (which isn't even completely correct, lol), but illustrates the point that nothing is emitted by the stream until a meaningful ast level has been reached.

**Comment by theqabalist** [comment]
To be clear though, I am not saying it's impossible.  I do think that it's feasible, to a degree, to implement a function that looks like `Parsimmon.Streams.parse(Readable) -> Readable` where it does this machinery for you, I'm just not sure that it really buys much beyond managing the timing/chunking concerns yourself, since at some point I assume it will need to be parameterized in order to change the different preferences for chunk boundary size, drop condition, etc.

Additionally, this introduces another weird concept I think, where parse errors cannot be promoted because they are partially expected.  So the output stream would potentially swallow errors that you want to know about (like a malformed parse at a top level vs an incorrect partial parse).

**Comment by njlr** [comment]
I suppose my suggestion is to allow usage like this: 

```javascript=
let state = null;

for (const c of input) {

  // Feed in one character from the current state
  const { nextState, result } = sexpr.parseFromState(state, c); 

  // result is truthy if we have matched an AST
  if (result) {
    console.log(result);
    state = null; // Reset the state to "nothing"
  } else {
    state = nextState;
  }

}
```

I don't know what `state` would look like exactly. It would somehow encode what is currently the internal state of a parser. 

----

As an aside, my implementation can be improved by splitting the chunks on the separation character (in my case `';'`). You only need to call `tryParse` when you might have reached the end of a statement.

**Comment by wavebeem** [comment]
I think you're asking for a way to suspend parsing and resume as more input is fed into the parser?

Like async parsing?

**Comment by wavebeem** [comment]
Closing this as it doesn't seem to be a good fit for Parsimmon right now.
