### ISSUE TITLE
Tie separator

### ISSUE THREAD

**Issue by ivan-kleshnin** [jneen/parsimmon#248]
Shouldn't `tie` accept an optional separator like `tie("\n")`? As it delegates to `.join` it seems pretty reasonable.

**Comment by wavebeem** [comment]
I've never actually wanted to use it that way, so I decided to keep it simpler and not have an argument. Can you show me an example where it's useful? Maybe I'd consider adding a `.tieWith(separator)`

**Comment by ivan-kleshnin** [comment]
```
let paragraph = line.sepBy1(P.nl).map(xs => xs.join("\n"))
// vs
let paragraph = line.sepBy1(P.nl).tie("\n")
```

**Comment by wavebeem** [comment]
ah, yeah i see. my intent behind `.tie()` was to help with long `seq(...)` of `string(...)` and `regexp(...)` parsers that need to be joined together. for your case you could also do `P.seq(line, P.nl).atLeast(1).tie()` for what it's worth (though that won't normalize the newlines for you, i guess).

i think i would be cool with `tieWith(separator)` but i prefer not to have optional arguments on methods so i think `tie(separator)` will have to just stay `tie()`…

that was always kind of a weird method for me to add too because i wanted to make it join and just mirror Array's join but we already have `join` as a fantasy land thing

**Comment by ivan-kleshnin** [comment]
I also try to avoid optional arguments in APIs, so I can see your point. 

Yeah `P.seq(line, P.nl).atLeast(1).tie()` is a bit different from `line.sepBy1(P.nl)` in that the first consumes a trailing newline and the second doesn't. I don't have enough experience to judge, but my current parsing habit is to avoid consuming separators as long as possible. I find it more controllable that way – most of my "wtf" moments were related to character overconsumption in some parser.

Anyway, I trust your decision on this one.

**Comment by ivan-kleshnin** [comment]
I'll submit a PR this weekend 👍
