### ISSUE TITLE
`sepBy` doesn't seem to backtrack, while `seq` and `then` do

### ISSUE THREAD

**Issue by mgreenbe** [jneen/parsimmon#279]
Should't the following either all succeed or all fail? It seems that `sepBy` isn't backtracking while `then` and `seq` are. Bug or by design?  What's Parsimmon's backtracking heuristic? Related: am I overlooking a combinator analogous to `try` in `parsec`?

```js
let NUM = P.digits;
let PLUS = P.string("+");
let TIMES = P.string("*");

{
  let SUM = P.sepBy(NUM, PLUS);
  let PROD = P.sepBy(NUM, TIMES);
  let EXPR = P.alt(SUM, PROD);
  console.log(EXPR.parse("0*1"));
// { status: false,
//  index: { offset: 1, line: 1, column: 2 },
//  expected: [ "'+'", 'EOF' ] }
}

{
  let SUM = NUM.sepBy(PLUS);
  let PROD = NUM.sepBy(TIMES);
  let EXPR = P.alt(SUM, PROD);
  console.log(EXPR.parse("0*1"));
// { status: false,
//  index: { offset: 1, line: 1, column: 2 },
//  expected: [ "'+'", 'EOF' ] }
}

{
  let SUM = NUM.then(PLUS).then(NUM);
  let PROD = NUM.then(TIMES).then(NUM);
  let EXPR = P.alt(SUM, PROD);
  console.log(EXPR.parse("0*1"));
// { status: true, value: '1' }
}

{
  let SUM = P.seq(NUM, PLUS, NUM);
  let PROD = P.seq(NUM, TIMES, NUM);
  let EXPR = P.alt(SUM, PROD);
  console.log(EXPR.parse("0*1"));
// { status: true, value: [ '0', '*', '1' ] }
}
```
[Love the library! Long time user, first time issue-raiser.]

**Comment by wavebeem** [comment]
Glad you're enjoying the library.

Backtracking is definitely a question that comes up a lot in here, but I'm pretty sure we're doing it "correctly". The issue with your example is that `alt` chooses the FIRST parser that succeeds, but in your first block the SUM parser will succeed having only parsed just `"0"`.

I also don't recommend using P.digits because that will also parse empty string.

I would refactor the code like this:

https://runkit.com/wavebeem/parsimmon-issue-279/1.0.0

I would say this is the preferred way to write a grammar for binary operators with precedence. Would you be interested in contributing a small example demonstrating it? I realize now that the current math example is a bit dense to read the first time given the use of reduce, so something more direct could be useful I think.

**Comment by wavebeem** [comment]
To add some more detail, P.alt is NOT failing. It is succeeding with just that "0", and then Parsimmon's .parse method is failing because we hit the end of a parse but there was still input remaining.

You can see this for yourself by calling `EXPR._(input, 0)` to call the parser's private method directly and bypass Parsimmon's EOF check where it gets status=true and value="0"

**Comment by mgreenbe** [comment]
Fantastic. Thank you! I'll see what I can do about contributing an example.
