### ISSUE TITLE
Question: What's wrong with my parser?

### ISSUE THREAD

**Issue by d4hines** [jneen/parsimmon#305]
Hi!
First _thank you_ for making this library. I've never done monadic parsing before, but it's so much easier than I thought it would be, and it gives me a lot of confidence knowing the whole thing is <1K lines of code.

I'm having some trouble with my parser: https://github.com/flamingo-lang/flamingo/blob/master/src/parse.ts#L144 For reference, it's for a logic programming language like Prolog. Here's the gist. I have _functions assignments_ of the form:
```
f(X, Y) = Z
```
There's also a shorthand. The term:
```
f(X, Y) = true
```
Can just be abbreviated as:
```
f(X, Y)
```
Likewise, 
```
f(X, Y) = false
```
can be written as
```
-f(X,Y)
```
These abbreviations are called function terms.

Together, function terms and function assignments are called function literals.
```
// all of these are function literals
f(X,Y) = Z,
f(X, Y),
-f(X, Y)
```
The problem I'm having is that sometimes comma separated sequences of function literals parse or don't parse depending on the relative order of function literals and function terms. E.g., when parsing `f(X, Y)`, the parser says "Hey, I expected an `=` and I got to the end.", like it forgot about function terms.

I haven't done extensive testing to figure out the exact conditions that produce the error, but I can if needed. I'm hoping though that this is some rookie mistake (I really don't understand parsers very well) that you can instantly identify in your expert wisdom.

Many thanks!

**Comment by wavebeem** [comment]
Cool project! I was working on a compile to JS language when I first got a good handle on Parsimmon. https://www.squiggle-lang.org/

## A few quick tips

- rather than `a.wrap(b, b)` you can do `a.trim(b)`
- your function `jump(a, b)` is the same as `a.then(b)`
- i would highly suggest calling `.map` BEFORE `.node` so you don't have to do so much object spreading everywhere

## About Parsimmon failures in general

there is quite a lot of parser to look at there, so is it possible you could narrow it down for me a bit? You can test any parser individually by calling it like `ALM.WhateverParser.tryParse(...)`

I will say that `P.alt` tends to be one of the hardest parts to use correctly. `P.alt` picks the _first_ choice that parses correctly, even if doing so ultimately causes everything to fail later.

For example:

```js
const parser = P.alt(
  P.string("a"),
  P.strign("ab")
);

parser.tryParse("ab")
```

Will fail, because `P.alt` picks the first parser that matches (`P.string("a")`), and then there's leftover unparsed data afterward.

## About your parser specifically

I think maybe your definition of FunctionAssignment and FunctionLiteral are a little confused, but it's a lot to wrap my head around in a jiffy.

The way I'm understanding this is (in pseudo code):

```
FunctionTerm =
  | f(X, Y)
  | -f(X, Y)

FunctionAssignment =
  | f(X, Y) = Z

FunctionLiteral =
  (FunctionAssignment | FunctionTerm) separated-by-commas
```

But in your code it seems like you've mixed those concepts up a bit:

FunctionAssignment for you starts with either a FunctionTerm or an Identifier, then `=` or `!=`, but is it possible to write `-f(X, Y) = Z`?

And looking at your defintion of FunctionLiteral, I would expect that to use `sepBy` at the top level, since it's multiple comma separated FunctionTerms of FunctionAssignments.

## Conclusion

Let me know if that helps. If you have the time to make a _smaller_ version of what you're working with that I can wrap my head around quicker, that would be helpful.

**Comment by d4hines** [comment]
Hi!

Thanks for all the advice. I had to take a break from this project for a bit, but I finally found some time to implement your suggested changes.

I've refactored the parser a bit. You were correct in observing that negation (`-`) doesn't make sense in a function assignment term. I've now structured FunctionLiterals as an `alt` between FunctionAssignments (unchanged), a new _BooleanFunctionTerm_, and a seq of negation and identifier (unchanged). I refactored FunctionAssignment to disallow negation, and structured BooleanFunctionTerm so it properly includes optional negation. That said, I'm still having the same issue as before, though now the parser is at least more correct.

I've made a new branch where everything is removed except the one failing test, and the code that supports it. (Run with `yarn test` if you're inclined). I'd be much obliged if you could look at it and set me straight.

Here's the link to the parser code: https://github.com/flamingo-lang/flamingo/blob/isolate-parse-error/src/parse.ts, and the test: https://github.com/flamingo-lang/flamingo/blob/isolate-parse-error/test/parse.test.ts

Thanks!

**Comment by wavebeem** [comment]
I took a quick look and started messing with your test.

Changing it to the following fixed the error.

```ts
ALM.Query.tryParse(`visible(Todo), active_filter = Filter, active(Todo).`)
```

Note that I removed all newlines and indentation.

There's a lot of parser to look through, so I didn't take the time to dig in to figure out why newlines are messing it up, but it seems even a single newline right at the beginning breaks the entire Query parser.

I also noticed that using a comma without a space after it causes your parser to fail. So I'd say you should examine anywhere whitespace is used. It tends to be one of the harder parts of parsers in my experience.
