### ISSUE TITLE
Incorrect error formatting

### ISSUE THREAD

**Issue by tagener-noisu** [jneen/parsimmon#336]
Hi, I noticed that there's a problem with error formatting. When I use `tryParse` method it gives me a nice error output and it shows me the exact position where the error has occured, except when the text uses tab characters.
```javascript
const parser = P.regex(/\s*foo/)
parser.tryParse('\t\tbar')
//Uncaught Error:
//-- PARSING FAILED --------------------------------------------------
//
//> 1 |           bar
//    | ^
```
As you can see the hat symbol ``^`` is in incorrect position, because the tab sybol counts as one column, and each column padded with only one space.

**Comment by wavebeem** [comment]
Hi @tagener-noisu

It's not possible format this message correctly without knowing the tab width of the document being parsed

You can use `.parse` instead and format the error message yourself. I know it's not as convenient, but I don't have any plans to work on supporting tabs in error formatting, especially since it would need to be configurable

**Comment by tagener-noisu** [comment]
I think it's easier than you might think. When you count the number of columns for the error result, you need to count number of tabs as well. And when you add padding to a hat symbol you just need to prepend that number of tabs as well. Since you don't add spaces but tabs, they will be displayed correctly, no matter what width is used by client.
Oh, it's ok. I might look into it in the future myself.

**Comment by wavebeem** [comment]
That's a clever solution, but the terminal environment may not have the same tab width as the document being parsed.

There's also countless Unicode characters that don't have width, or have double width. Getting the caret always lined up can be pretty tricky haha.

**Comment by anko** [comment]
I suggest we replace common non-printing characters with appropriate Unicode characters in error messages.  The errors are clearer if common invisible characters are made visible, and there's no problem with tab size then.

```js
const replaceUnprintables = (str) => {
  return str.split('').map((c) => {
    // Display newlines and tabs using arrows
    if (c === '\n') { return '⏎' }
    if (c === '\t') { return '↹' }

    // Display spaces using a space marker
    if (c === ' ') { return '␣' }

    // Display control characters from the C0 control code block (ASCII 0–31)
    // using the Unicode Control Pictures block.  The Control Pictures are in
    // the same order, just offset.
    const charCode = c.charCodeAt()
    if (charCode <= 31) { return String.fromCharCode(0x2400 + charCode) }

    // Display anything else normally.
    return c
  }).join('')
}
```

- - -

Of course because Unicode is so funktastically quirky, anything you can say about it is wrong, so this does not deal with the full horror list of stuff like half-width kana, vertical RTL text flow direction markers, stacked combining diacriticals, and emoji gender and skin-colour modifiers. And I don't think any terminal emulator can even display those correctly! :sweat_smile:

**Comment by wavebeem** [comment]
It's not really something I'm interested in chasing. Like you said, Unicode makes this problem go from hard to extremely hard, haha 😆
