### ISSUE TITLE
Performance comparison (benchmarks)

### ISSUE THREAD

**Issue by jirutka** [jneen/parsimmon#66]
This library looks very interesting, thanks for it!

I have a question, how is the resulting parser CPU and memory efficient in comparison with other JS parsers? It would be very useful to provide some benchmarks for performance comparison.

**Comment by anko** [comment]
I haven't run benchmarks, but have an idea:

[Eslisp](https://github.com/anko/eslisp)'s parser started out as a custom library-less parser, which I ported first to Parsimmon, then to [PEG.js](https://github.com/pegjs/pegjs). For a while, all 3 implementations shared the same set of tests, and they're all completely separate modules from the rest of the language implementation.

I haven't benchmarked them, but I think they'd make a good benchmark. If you want to have a go at it, you can find the different versions at these commits:

 - [Custom parser](https://github.com/fwg/s-expression/tree/b4d2647dd6fe13ce99f781c08926accd82eb8c0e)
 - [Parsimmon port](https://github.com/anko/sexpr-plus/tree/f1f060bab2999a8e0c88349bf2435a4174ffec49)
 - [PEG.js port](https://github.com/anko/sexpr-plus/tree/948b12e7cb78718fbba8dbf29036c7329063627e)

They should all pass the custom parser's tests.

**Comment by wavebeem** [comment]
I definitely approve of having some kind of performance demonstration, but it's not on the top of my priority list.

**Comment by wavebeem** [comment]
I don't have any plans to address this in the near future, so I'm going to close this. If someone else is interested, I'm happy to publish results.

**Comment by bd82** [comment]
I have created such a benchmark(cpu only) to compare my own parsing library to others.
There are currently  a  total of **seven** different parsing libraries tested. 
The benchmark involves parsing a 1,000 lines **Json** sample.
Json was chosen because most javascript parsing libraries provide a json grammar as an example

You can run the benchmark here:
http://sap.github.io/chevrotain/performance/
Note that there may be very different results depending on the browser used.

**Comment by jirutka** [comment]
@bd82 Great work, thanks a lot!

**Comment by wavebeem** [comment]
Ooh. This is very cool. Do you mind if I link to this in the Parsimmon README?

**Comment by bd82** [comment]
@jirutka thanks. It needs a prettier UI but that will come whenever jsperf.com will be online again...
@wavebeem sure no problem. It is all open source (Apache) anyhow...

And also I forgot to thank @firasnajjar who helped me create it in the first place.

I just had a random thought of also comparing an hand built parser to the parsing libraries/ generators...

**Comment by jirutka** [comment]
> It needs a prettier UI…

Come one, it’s just a benchmark, it doesn’t need fancy UI, logo and stuff. ;) The most important is accuracy. Also some text about how does it work would be helpful, to increase credibility.

**Comment by bd82** [comment]
> Come one, it’s just a benchmark, it doesn’t need fancy UI, logo and stuff. ;) The most important is accuracy. Also some text about how does it work would be helpful, to increase credibility.

You are right, I'm just a little spoiled because the original version was on JSPerf.com 
with pretty colorful graphs and a "re-run" button.
I'll recreate it on JSPerf.com V2 whenever it is out...


I've added a line stating that [benchmark.js](https://benchmarkjs.com/) is used to perform the
benchmarks. Is there anything other information I can add regarding credibility ?
I've already include a link to the whole source code...

**Comment by wavebeem** [comment]
@bd82 My only important suggestion is put a button to run the benchmarks instead of auto-starting on page load. It's pretty disruptive to have a page instantly peg your CPU when you arrive.

**Comment by firasnajjar** [comment]
@bd82 Define the prettier UI and I'll implement it :)

**Comment by bd82** [comment]
@wavebeem That's a good idea.
Opened an [issue](https://github.com/SAP/chevrotain/issues/238) for that.

@firasnajjar Thanks.

I think continued discussions on specifics on improving the benchmarks (if needed) should be moved outside this thread as we are going a bit off topic?

**Comment by wavebeem** [comment]
Agreed @bd82. I'm just leaving this thread open as a reminder so I can add a link to your benchmark into the README later. Thanks again!

**Comment by wavebeem** [comment]
Thanks again @bd82 for helping out with this issue!!
