### ISSUE TITLE
.optional() method

### ISSUE THREAD

**Issue by pandanoir** [jneen/parsimmon#82]
I often want a optional parser. Now I use .times(0, 1) for this. However, .times(0, 1) doesn't seem to mean optional. When you read code and find .times(0, 1), can you see that .times(0, 1) creates optional parser?

I suggest .optional() method that is equal to .times(0, 1).

**Comment by wavebeem** [comment]
I often want that also, but using .`optional()` to mean `.times(0, 1)` gives you either `[]` or `[result]` back. This is ok, but I often want to get `null` or even `""` back from an optional parser.

Because of this, I use this pattern:

```js
someParser.or(P.of("")) // result OR empty string

someParser.or(P.of(null)) // result OR null

someParser.times(0, 1) // [result] OR []
```

I feel like if I add `.optional`, it doesn't make sense to pick any one of those three to be the return value. What do you think about that?

**Comment by pandanoir** [comment]
I'm agree with you. `.optional()` should return not \[] but ''.

**Comment by wavebeem** [comment]
I know PEG.js uses `null` for its "optional" feature, so that's my inclination. I think it might make sense to put in the docs a note saying to use `.or(P.of(""))` if you want a string, or `.times(0, 1)` if you want an array.

```js
var IfStatement= P.seqMap(
  IfBranch,
  ElseBranch.optional(),
  (If, Else) => ({Type: "IfStatement", If, Else})
);
```

I think it would be really weird if you got an empty string there, and it would be hard to notice your mistake.

```js
var Number = P.seqMap(
  P.regex(/[0-9]+/),
  P.regex(/\.[0-9]+/)
).map((integer, fractional) => integer + (fractional || ""));
```

It's easy to just use `|| ""` in the case where you have null there, or just use .`or(P.of(""))` like suggested

```js
var Number = P.seqMap(
  P.regex(/[0-9]+/),
  P.regex(/\.[0-9]+/).or(P.of(""))
).map((integer, fractional) => +(integer + fractional));
```

Or maybe there could be an `.else` method?

```js
P.regex(/\.[0-9]+/).else(() => "")
```

It's hard for me to pick what's best in this case >_<
